# Generated by Django 6.0.5 on 2026-05-30 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_remove_subject_unique_subject_code_per_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAIAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequently_missed_topics', models.TextField(blank=True)),
                ('at_risk_students', models.TextField(blank=True)),
                ('interventions', models.TextField(blank=True)),
                ('learning_trends', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analytics', to='classroom.classroom')),
            ],
        ),
    ]
