# Generated by Django 6.0.5 on 2026-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='extra_questions',
            field=models.TextField(blank=True, help_text='Generated Short/Long questions'),
        ),
    ]
