# Generated by Django 6.0.5 on 2026-05-30 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_job', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap_html', models.TextField(blank=True, help_text='Generated roadmap in HTML')),
                ('skills_required', models.TextField(blank=True, help_text='HTML formatted list of skills required')),
                ('project_suggestions', models.TextField(blank=True, help_text='HTML formatted project suggestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ats_score', models.IntegerField(blank=True, null=True)),
                ('analysis_results', models.TextField(blank=True, help_text='HTML formatted analysis results')),
                ('improvement_suggestions', models.TextField(blank=True, help_text='HTML formatted improvement suggestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Resume Analyses',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
