# Generated by Django 6.0.5 on 2026-05-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subject',
            name='unique_subject_code_per_teacher',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
